---
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🧹 Maintenance'
    labels:
      - 'chore'
      - 'docs'
      - 'ci'
template: |
  ## What's Changed

  $CHANGES
