---
run:
  skip-go-version-check: true

linters-settings:
  gocyclo:
    min-complexity: 15

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - revive
    - gocyclo
    - unconvert
    - ineffassign
    - tparallel
    - govet
    - unused
