---
version: "2"

run:
  timeout: 5m

issues:
  exclude-rules:
    - path: cmd/
      linters:
        - gocyclo
        - revive
        - unused

linters-settings:
  gocyclo:
    min-complexity: 15

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - revive
    - gocyclo
    - unconvert
    - ineffassign
    - tparallel
    - govet
    - unused
