---
version: "2"

run:
  go: "1.24"
  timeout: 5m
  skip-dirs:
    - "vendor"
    - "third_party"
  tests: true

linters:
  default: "fast"
  enable:
    - govet
    - staticcheck
    - unused
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - ineffassign
  disable:
    - maligned
    - gochecknoglobals

linters-settings:
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: "github.com/estudosdevops/opsmaster"

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: strict

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "should have comment or be unexported"
  exclude-rules:
    - linters:
        - revive
      text: "should have comment"

output:
  format: colored-line-number
  sort-results: true
  uniq-by-line: true
