# OpsMaster Configuration File

# AWS Configuration
aws:
  region: us-east-1
  profile: default

# Docker Configuration
docker:
  registry: docker.io
  username: your-username

# Kubernetes Configuration
kubernetes:
  context: minikube
  namespace: default

# Git Configuration
git:
  default_branch: main
  commit_template: |
    feat: %s

# Notification Settings
notifications:
  slack:
    webhook_url: https://hooks.slack.com/services/xxx/yyy/zzz
    channel: "#devops"
  email:
    smtp_server: smtp.gmail.com
    smtp_port: 587
    from: your-email@gmail.com

# Custom Paths
paths:
  workspace: ~/workspace
  logs: /var/log/opsmaster
  templates: ~/.opsmaster/templates 