services:
  postgres_source:
    image: postgres:15
    container_name: postgres_source
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sourcedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_source_data:/var/lib/postgresql/data
      - ./init-scripts/init-data.sql:/docker-entrypoint-initdb.d/01-init-data.sql

  postgres_target:
    image: postgres:15
    container_name: postgres_target
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: targetdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_target_data:/var/lib/postgresql/data

volumes:
  postgres_source_data:
  postgres_target_data: