name: 🧪 Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: unit-tests-${{ github.ref }}

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
          cache-dependency-path: go.sum

      - name: Install gotestsum for better test output
        run: go install gotest.tools/gotestsum@latest

      - name: Run Linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.2.2

      - name: Run Tests
        run: go list ./... | grep -v '/cmd' | xargs gotestsum --format=short-verbose -- -cover -race
