name: 🧪 Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: unit-tests-${{ github.ref }}

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install richgo for colored test output
        run: go install github.com/kyoh86/richgo@latest

      - name: Run Linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v1.59

      - name: Run Tests
        run: go list ./... | grep -v '/cmd' | xargs richgo test -v -cover -race
